data_path: c:\files\dev\taxman-data
play-pass:
  exclude_before: 2020-07
nintendo:
  exclude_before: 2019-11
steam:
  exclude_before: 2014-01
  exclude_steam_direct_fee: True
  exclude_soundtrack: True

title_remap:
  com.grapefrukt.games.bore: holedown
  com.grapefrukt.games.rymdkapsel1: rymdkapsel
  com.grapefrukt.games.twofold: twofold inc.
  tilebreaker: subpar pool
  com.grapefrukt.games.rymdkapsel1: rymdkapsel
  extended-universe: extended universe bundle